version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - .docker/db:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    container_name: redis_container
    command: >
          --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - '6379:6379'

volumes:
  .docker:
